# sonic broadcom one image installer

SONIC_ONE_NBI_IMAGE = sonic-nbi-broadcom.bin
$(SONIC_ONE_NBI_IMAGE)_MACHINE = broadcom
$(SONIC_ONE_NBI_IMAGE)_IMAGE_TYPE = nbi

CISCO_NBI_PACKAGE = cisco-nbi-package_1.0_amd64.deb
$(CISCO_NBI_PACKAGE)_PATH = $(PLATFORM_PATH)

SONIC_COPY_DEBS += $(CISCO_NBI_PACKAGE)
SONIC_STRETCH_DEBS += $(CISCO_NBI_PACKAGE)

$(SONIC_ONE_NBI_IMAGE)_INSTALLS += $(BRCM_OPENNSL_KERNEL) $(CISCO_NBI_PACKAGE)
$(SONIC_ONE_NBI_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)

$(SONIC_ONE_NBI_IMAGE)_LAZY_INSTALLS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_N3132_PLATFORM_MODULE)

$(SONIC_ONE_NBI_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)
SONIC_INSTALLERS += $(SONIC_ONE_NBI_IMAGE)
