# sonic broadcom one image installer

SONIC_ONE_NBI_IMAGE = sonic-nbi-broadcom.bin
$(SONIC_ONE_NBI_IMAGE)_MACHINE = broadcom
$(SONIC_ONE_NBI_IMAGE)_IMAGE_TYPE = nbi
$(SONIC_ONE_NBI_IMAGE)_INSTALLS += $(BRCM_OPENNSL_KERNEL) $(CISCO_N3132_PLATFORM_MODULE) $(CISCO_NBI_PACKAGE)
$(SONIC_ONE_NBI_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)
SONIC_INSTALLERS += $(SONIC_ONE_NBI_IMAGE)
