CISCO_N9200_PLATFORM_MODULE_VERSION = 1.0

export CISCO_N9200_PLATFORM_MODULE_VERSION

CISCO_N9200_PLATFORM_MODULE = platform-modules-n9200_$(CISCO_N9200_PLATFORM_MODULE_VERSION)_amd64.deb
$(CISCO_N9200_PLATFORM_MODULE)_PATH = $(PLATFORM_PATH)

CISCO_PYTHON_PLATFORM_MODULE = python-platform-cisco_1.0-1_all.deb
$(CISCO_PYTHON_PLATFORM_MODULE)_PATH = $(PLATFORM_PATH)

CISCO_NBI_PACKAGE = cisco-nbi-package_1.0_amd64.deb
$(CISCO_NBI_PACKAGE)_PATH = $(PLATFORM_PATH)

SONIC_COPY_DEBS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_PYTHON_PLATFORM_MODULE) $(CISCO_NBI_PACKAGE)
SONIC_STRETCH_DEBS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_PYTHON_PLATFORM_MODULE) $(CISCO_NBI_PACKAGE)

