variables:
  ${{ if eq(variables['Build.Reason'],'PullRequest') }}:
    VERSION_CONTROL_OPTIONS: 'SONIC_VERSION_CONTROL_COMPONENTS=$([[ $(System.PullRequest.TargetBranch) =~ ^refs/heads/internal-20[2-9][0-9]{3}$ ]] && echo deb,py2,py3,web,git,docker || echo none)'
  ${{ elseif ne(variables['Build.SourceBranchName'],'internal') }}:
    VERSION_CONTROL_OPTIONS: 'SONIC_VERSION_CONTROL_COMPONENTS=$([[ $(Build.SourceBranchName) =~ ^internal-20[2-9][0-9]{3}$ ]] && echo deb,py2,py3,web,git,docker || echo none)'
  ${{ else }}:
    VERSION_CONTROL_OPTIONS: ''
