resources:
  repositories:
  - repository: buildimage
    type: github
    name: StormLiangMS/sonic-buildimage
    ref: refs/heads/feature/dhcp-match-mode-phase6
    endpoint: sonic-net

trigger: none
pr: none

variables:
- template: .azure-pipelines/template-variables.yml@buildimage

stages:
- stage: Build
  pool: sonicso1ES-amd64
  variables:
  - group: Container-Registry
  - name: CACHE_MODE
    value: wcache
  - template: .azure-pipelines/azure-pipelines-repd-build-variables.yml@buildimage
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) INCLUDE_DHCP_SERVER=y ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobFilters: none
